-- Considerar las claves primarias deben ser auto-incrementables.
-- El número de pedido es un número que se incrementa de 10 en 10.
-- Los nombres de las restricciones de PK y FK deben coincidir con lo indicado en el modelo.
-- Asignar restricción NOT NULL a las columnas que corresponda.
-- El valor por defecto para la fecha de contrato del empleado será la fecha de la base de datos (sistema).
-- Al finalizar la actividad valide su script usando la herramienta Oracle SQL Developer. El código se debe ejecutar de una vez y en forma secuencial.

CREATE TABLE cliente (
    id_cliente NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primer_nombre VARCHAR(25) NOT NULL,
    segundo_nombre VARCHAR(25),
    apell_materno VARCHAR(25) NOT NULL,
    apell_paterno VARCHAR(25) NOT NULL,
    direccion VARCHAR(30) NOT NULL,
    fecha_contrato DATE DEFAULT SYSDATE
);


CREATE TABLE pedido (
    nro_pedido NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_pedido DATE NOT NULL,
    fecha_entrega DATE NOT NULL,
    id_cliente NUMBER(5) NOT NULL,
    id_empleado NUMBER(6) NOT NULL,
    CONSTRAINT fk_cliente_pedido FOREIGN KEY (id_cliente) 
    CONSTRAINT fk_empleado_pedido FOREIGN KEY (id_empleado) 
);

CREATE TABLE empleado (
    id_empleado NUMBER(6) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primer_nombre VARCHAR(25) NOT NULL,
    segundo_nombre VARCHAR(25),
    apell_materno VARCHAR(25) NOT NULL,
    apell_paterno VARCHAR(25) NOT NULL,
    fecha_contrato DATE NOT NULL
);