-- DDL - Data Description Language
-- DML - Data Manipulation Language
-- TCL - Transaction Control Language
-- 
-- USER SQL
CREATE USER "NUEVO_USUARIO" IDENTIFIED BY "Clave1Clase6"  
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "NUEVO_USUARIO" ;
GRANT "RESOURCE" TO "NUEVO_USUARIO" ;

-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO "NUEVO_USUARIO" ;
